import type { Finding, Severity, FindingSummary, EngineFailure } from '../types/finding.js';

export type ReportLang = 'en' | 'es';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

type TranslationStrings = {
  title: string;
  summary: string;
  severityLabel: string;
  countLabel: string;
  totalLabel: string;
  fieldLabel: string;
  valueLabel: string;
  fileLabel: string;
  ruleLabel: string;
  cweLabel: string;
  engineLabel: string;
  explanationLabel: string;
  suggestionLabel: string;
  criticalFindings: string;
  highFindings: string;
  mediumFindings: string;
  lowInfoFindings: string;
  npmAudit: string;
  packageLabel: string;
  cveLabel: string;
  fixAvailableLabel: string;
  autoFixableLabel: string;
  yes: string;
  no: string;
  filesScanned: string;
  statusLabel: string;
  findingsLabel: string;
  ok: string;
  failed: string;
  allClear: string;
  enginesIncomplete: string;
  zeroFindingsEnginesFailed: string;
  criticalAlert: (n: number) => string;
  engineFailed: string;
  generatedBy: (v: string) => string;
  metaRepo: string;
  metaBranch: string;
  metaCommit: string;
  metaScanPath: string;
  metaDate: string;
  severityLabels: Record<Severity, string>;
  jobSummaryFooter: string;
};

const translations: Record<ReportLang, TranslationStrings> = {
  en: {
    title: 'AuditGuard Security Report',
    summary: 'Summary',
    severityLabel: 'Severity',
    countLabel: 'Count',
    totalLabel: 'Total',
    fieldLabel: 'Field',
    valueLabel: 'Value',
    fileLabel: 'File',
    ruleLabel: 'Rule',
    cweLabel: 'CWE',
    engineLabel: 'Engine',
    explanationLabel: 'Explanation:',
    suggestionLabel: 'Suggestion:',
    criticalFindings: 'Critical Findings',
    highFindings: 'High Findings',
    mediumFindings: 'Medium Findings',
    lowInfoFindings: 'Low/Info Findings',
    npmAudit: 'npm audit',
    packageLabel: 'Package',
    cveLabel: 'CVE',
    fixAvailableLabel: 'Fix Available',
    autoFixableLabel: 'Auto-fixable',
    yes: 'Yes',
    no: 'No',
    filesScanned: 'Files Scanned',
    statusLabel: 'Status',
    findingsLabel: 'Findings',
    ok: 'OK',
    failed: 'FAILED',
    allClear: 'No security vulnerabilities detected. All clear!',
    enginesIncomplete: 'Results below are incomplete. Investigate engine failures before relying on this report.',
    zeroFindingsEnginesFailed: '**0 findings detected, but some engines failed.** Results are incomplete and cannot be trusted as clean.',
    criticalAlert: (n: number) => `**${n} CRITICAL finding(s) detected.** CI will fail until resolved.`,
    engineFailed: 'failed to run:',
    generatedBy: (v: string) => `*Generated by [AuditGuard](https://github.com/org/auditguard) ${v}*`,
    metaRepo: 'Repo:',
    metaBranch: 'Branch:',
    metaCommit: 'Commit:',
    metaScanPath: 'Scan path:',
    metaDate: 'Date:',
    severityLabels: {
      critical: 'CRITICAL',
      high: 'HIGH',
      medium: 'MEDIUM',
      low: 'LOW',
      info: 'INFO',
    },
    jobSummaryFooter: 'Job summary generated at run-time',
  },
  es: {
    title: 'AuditGuard Informe de Seguridad',
    summary: 'Resumen',
    severityLabel: 'Severidad',
    countLabel: 'Cantidad',
    totalLabel: 'Total',
    fieldLabel: 'Campo',
    valueLabel: 'Valor',
    fileLabel: 'Archivo',
    ruleLabel: 'Regla',
    cweLabel: 'CWE',
    engineLabel: 'Motor',
    explanationLabel: 'Explicación:',
    suggestionLabel: 'Sugerencia:',
    criticalFindings: 'Hallazgos Críticos',
    highFindings: 'Hallazgos Altos',
    mediumFindings: 'Hallazgos Medios',
    lowInfoFindings: 'Hallazgos Bajos/Informativos',
    npmAudit: 'auditoría npm',
    packageLabel: 'Paquete',
    cveLabel: 'CVE',
    fixAvailableLabel: 'Corrección Disponible',
    autoFixableLabel: 'Auto-corregible',
    yes: 'Sí',
    no: 'No',
    filesScanned: 'Archivos Escaneados',
    statusLabel: 'Estado',
    findingsLabel: 'Hallazgos',
    ok: 'OK',
    failed: 'FALLÓ',
    allClear: 'No se detectaron vulnerabilidades de seguridad. ¡Todo limpio!',
    enginesIncomplete: 'Los resultados a continuación están incompletos. Investigue los fallos de los motores antes de confiar en este informe.',
    zeroFindingsEnginesFailed: '**0 hallazgos detectados, pero algunos motores fallaron.** Los resultados están incompletos y no se puede confiar en que estén limpios.',
    criticalAlert: (n: number) => `**${n} hallazgo(s) CRÍTICO(s) detectado(s).** El CI fallará hasta que se resuelva.`,
    engineFailed: 'falló al ejecutar:',
    generatedBy: (v: string) => `*Generado por [AuditGuard](https://github.com/org/auditguard) ${v}*`,
    metaRepo: 'Repositorio:',
    metaBranch: 'Rama:',
    metaCommit: 'Commit:',
    metaScanPath: 'Ruta escaneada:',
    metaDate: 'Fecha:',
    severityLabels: {
      critical: 'CRÍTICA',
      high: 'ALTA',
      medium: 'MEDIA',
      low: 'BAJA',
      info: 'INFO',
    },
    jobSummaryFooter: 'Resumen del trabajo generado en tiempo de ejecución',
  },
};

function t(lang: ReportLang): TranslationStrings {
  return translations[lang] || translations.en;
}

function escapeMarkdown(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|')
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]')
    .replace(/\*/g, '\\*')
    .replace(/_/g, '\\_')
    .replace(/~/g, '\\~')
    .replace(/`/g, '\\`')
    .replace(/#/g, '\\#')
    .replace(/</g, '\\<')
    .replace(/>/g, '\\>')
    .replace(/\n/g, ' ');
}

function generateSummary(findings: Finding[]): FindingSummary {
  const bySeverity: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  const byEngine: Record<string, number> = { eslint: 0, semgrep: 0, 'npm-audit': 0 };
  const byFile: Record<string, number> = {};

  for (const f of findings) {
    bySeverity[f.severity]++;
    byEngine[f.engine]++;
    byFile[f.file] = (byFile[f.file] || 0) + 1;
  }

  return {
    total: findings.length,
    bySeverity,
    byEngine: byEngine as Finding['engine'][] extends never ? Record<string, number> : Record<string, number>,
    byFile,
  };
}

function generateSummaryTable(findings: Finding[], tr: typeof translations.en): string {
  const summary = generateSummary(findings);

  let md = `| ${tr.severityLabel} | ${tr.countLabel} |\n`;
  md += '|----------|-------|\n';
  for (const sev of SEVERITY_ORDER) {
    if (summary.bySeverity[sev] > 0) {
      md += `| ${SEVERITY_EMOJI[sev]} ${tr.severityLabels[sev]} | ${summary.bySeverity[sev]} |\n`;
    }
  }
  md += `| **${tr.totalLabel}** | **${summary.total}** |\n`;
  return md;
}

function generateFindingBlock(finding: Finding, tr: typeof translations.en): string {
  let md = `### ${finding.id} — ${escapeMarkdown(finding.message)}\n\n`;
  md += `| ${tr.fieldLabel} | ${tr.valueLabel} |\n`;
  md += '|-------|------|\n';
  md += `| **${tr.severityLabel}** | ${SEVERITY_EMOJI[finding.severity]} ${tr.severityLabels[finding.severity]} |\n`;
  md += `| **${tr.fileLabel}** | \`${finding.file}:${finding.line}\` |\n`;
  md += `| **${tr.ruleLabel}** | \`${finding.rule}\` |\n`;
  if (finding.cwe) {
    const link = finding.cweUrl ? `[${finding.cwe}](${finding.cweUrl})` : finding.cwe;
    md += `| **${tr.cweLabel}** | ${link} |\n`;
  }
  md += `| **${tr.engineLabel}** | ${finding.engine} |\n\n`;
  md += `**${tr.explanationLabel}** ${finding.explanation}\n\n`;
  md += `**${tr.suggestionLabel}** ${finding.suggestion}\n`;
  return md;
}

function generateNpmAuditTable(findings: Finding[], tr: typeof translations.en): string {
  const npmFindings = findings.filter((f) => f.engine === 'npm-audit');
  if (npmFindings.length === 0) return '';

  let md = `## ${tr.npmAudit}\n\n`;
  md += `| ${tr.packageLabel} | ${tr.severityLabel} | ${tr.cveLabel} | ${tr.fixAvailableLabel} | ${tr.autoFixableLabel} |\n`;
  md += '|---------|----------|-----|---------------|--------------|\n';

  for (const f of npmFindings) {
    const pkg = f.rule.replace('npm-audit/', '');
    const cwe = f.cwe ? `[${f.cwe}](${f.cweUrl || '#'})` : 'N/A';
    md += `| ${pkg} | ${tr.severityLabels[f.severity]} | ${cwe} | ${f.fixAvailable ? tr.yes : tr.no} | ${f.autoFixEligible ? tr.yes : tr.no} |\n`;
  }

  return md;
}

function generateFilesScannedSummary(findings: Finding[], engineFailures: EngineFailure[], tr: typeof translations.en): string {
  const engines = ['eslint', 'semgrep', 'npm-audit'] as const;
  const failedEngines = new Set(engineFailures.map((f) => f.engine));

  let md = `## ${tr.filesScanned}\n\n`;
  md += `| ${tr.engineLabel} | ${tr.statusLabel} | ${tr.findingsLabel} |\n`;
  md += '|--------|--------|----------|\n';

  for (const engine of engines) {
    const count = findings.filter((f) => f.engine === engine).length;
    const status = failedEngines.has(engine) ? tr.failed : tr.ok;
    md += `| ${engine} | ${status} | ${count} |\n`;
  }

  return md;
}

export function generateMarkdownReport(
  findings: Finding[],
  meta: {
    repo?: string;
    branch?: string;
    commit?: string;
    scanPath?: string;
  } = {},
  engineFailures: EngineFailure[] = [],
  lang: ReportLang = 'en',
): string {
  const tr = t(lang);
  const summary = generateSummary(findings);

  let md = `# ${tr.title}\n\n`;

  if (engineFailures.length > 0) {
    md += '> [!WARNING]\n';
    for (const f of engineFailures) {
      md += `> **${f.engine}** ${tr.engineFailed} ${f.error}\n`;
    }
    md += `> ${tr.enginesIncomplete}\n\n`;
  }

  if (meta.repo) md += `**${tr.metaRepo}** ${meta.repo}\n`;
  if (meta.branch) md += `**${tr.metaBranch}** ${meta.branch}\n`;
  if (meta.commit) md += `**${tr.metaCommit}** ${meta.commit}\n`;
  if (meta.scanPath) md += `**${tr.metaScanPath}** \`${meta.scanPath}\`\n`;
  md += `**${tr.metaDate}** ${new Date().toISOString()}\n`;
  md += '\n---\n\n';

  md += `## ${tr.summary}\n\n`;
  md += generateSummaryTable(findings, tr);
  md += '\n';

  if (summary.total === 0 && engineFailures.length === 0) {
    md += '> [!NOTE]\n';
    md += `> ${tr.allClear}\n\n`;
  }

  if (summary.total === 0 && engineFailures.length > 0) {
    md += '> [!CAUTION]\n';
    md += `> ${tr.zeroFindingsEnginesFailed}\n\n`;
  }

  if (summary.bySeverity.critical > 0) {
    md += '> [!CAUTION]\n';
    md += `> ${tr.criticalAlert(summary.bySeverity.critical)}\n\n`;
  }

  const criticalFindings = findings.filter((f) => f.severity === 'critical');
  if (criticalFindings.length > 0) {
    md += `## ${tr.criticalFindings}\n\n`;
    for (const f of criticalFindings) {
      md += generateFindingBlock(f, tr) + '\n\n---\n\n';
    }
  }

  const highFindings = findings.filter((f) => f.severity === 'high');
  if (highFindings.length > 0) {
    md += `## ${tr.highFindings}\n\n`;
    for (const f of highFindings) {
      md += generateFindingBlock(f, tr) + '\n\n---\n\n';
    }
  }

  const mediumFindings = findings.filter((f) => f.severity === 'medium');
  if (mediumFindings.length > 0) {
    md += `<details>\n<summary>${tr.mediumFindings} (${mediumFindings.length})</summary>\n\n`;
    for (const f of mediumFindings) {
      md += generateFindingBlock(f, tr) + '\n\n';
    }
    md += '</details>\n\n';
  }

  const lowFindings = findings.filter((f) => f.severity === 'low' || f.severity === 'info');
  if (lowFindings.length > 0) {
    md += `<details>\n<summary>${tr.lowInfoFindings} (${lowFindings.length})</summary>\n\n`;
    for (const f of lowFindings) {
      md += generateFindingBlock(f, tr) + '\n\n';
    }
    md += '</details>\n\n';
  }

  const npmSection = generateNpmAuditTable(findings, tr);
  if (npmSection) {
    md += '\n---\n\n' + npmSection;
  }

  md += '\n---\n\n';
  md += generateFilesScannedSummary(findings, engineFailures, tr);

  md += '\n---\n\n';
  md += `${tr.generatedBy('v0.1.0')}\n`;
  md += `${tr.jobSummaryFooter}\n`;

  return md;
}
